"""Extension preset categories, one per ExtensionType (14 total).

Entity-only extension types are valid on both MLO entities and map entities

Each category captures only the type-specific sub-PropertyGroup (e.g.
`door_extension_properties`) of the wrapping `ExtensionProperties`, not all 14
sub-pointers. These property groups define `__sz_preset_capture__` to indicate
which properties need to be saved.

All operator and panel classes are generated by the factory and injected into
this module's `globals()` so that `auto_load` discovers them.
"""

from dataclasses import dataclass
from pathlib import Path

import bpy

from ....shared.presets import (
    PresetCategory,
    register_preset_category,
    PresetSaveOperatorBase,
    PresetLoadOperatorBase,
    PresetDeleteOperatorBase,
    PresetPanel,
)
from ....ymap_next import context as map_context
from ...properties.extensions import ExtensionType
from ...utils import get_selected_extension, get_selected_entity_extension


# Host identifier used by ExtensionsPanelHelper.draw to pick the right panel
# from EXTENSION_PRESET_PANEL_BY_TYPE_AND_HOST.
HOST_ARCHETYPE = "archetype"
HOST_MLO_ENTITY = "mlo_entity"
HOST_MAP_ENTITY = "map_entity"


@dataclass
class _ExtDef:
    ext_type: ExtensionType
    label: str


# Archetype-only extension types.
_ARCHETYPE_EXTENSIONS = [
    _ExtDef(ExtensionType.PARTICLE, "Particle"),
    _ExtDef(ExtensionType.AUDIO_COLLISION, "Audio Collision"),
    _ExtDef(ExtensionType.AUDIO_EMITTER, "Audio Emitter"),
    _ExtDef(ExtensionType.EXPLOSION_EFFECT, "Explosion"),
    _ExtDef(ExtensionType.LADDER, "Ladder"),
    _ExtDef(ExtensionType.BUOYANCY, "Buoyancy"),
    _ExtDef(ExtensionType.LIGHT_SHAFT, "Light Shaft"),
    _ExtDef(ExtensionType.SPAWN_POINT, "Spawn Point"),
    _ExtDef(ExtensionType.WIND_DISTURBANCE, "Wind Disturbance"),
    _ExtDef(ExtensionType.PROC_OBJECT, "Procedural Object"),
    _ExtDef(ExtensionType.EXPRESSION, "Expression"),
]


# Entity-only types. Each gets one shared category and two host bindings
# (MLO entity context vs map entity context).
_ENTITY_EXTENSIONS = [
    _ExtDef(ExtensionType.DOOR, "Door"),
    _ExtDef(ExtensionType.SPAWN_POINT_OVERRIDE, "Spawn Point Override"),
    _ExtDef(ExtensionType.LIGHT_EFFECT, "Light Effect"),
]


# Dispatch table populated by the factory. Read by ExtensionsPanelHelper.draw
# to pick the right popover panel for the active extension + host context.
EXTENSION_PRESET_PANEL_BY_TYPE_AND_HOST: dict[tuple[ExtensionType, str], type] = {}


def _make_get_target(ext_type: ExtensionType, container_accessor):
    """Returns a context -> sub-PropertyGroup callable.

    The container_accessor returns the wrapping `ExtensionProperties`; we then
    check it is the right type and return its type-specific sub-PropertyGroup.
    """

    def _get_target(context):
        ext = container_accessor(context)
        if ext is None or ext.extension_type != ext_type:
            return None
        return ext.get_properties()

    return _get_target


def _make_poll(ext_type: ExtensionType, container_accessor, label: str):
    """Returns a (ok, reason) poll matching the get_target above."""

    def _poll(context):
        ext = container_accessor(context)
        if ext is None or ext.extension_type != ext_type:
            return False, f"Select a {label.lower()} extension."
        return True, ""

    return _poll


def _make_op_poll(get_target_fn, label: str):
    """Returns a classmethod-suitable poll function for an operator subclass
    that overrides get_target."""

    @classmethod
    def poll(cls, context):
        if get_target_fn(context) is None:
            cls.poll_message_set(f"Select a {label.lower()} extension.")
            return False
        return True

    return poll


def _id_for(ext_type: ExtensionType) -> str:
    return f"extension_{ext_type.name.lower()}"


def _make_archetype_classes(edef: _ExtDef):
    """Create category + 3 operators + 1 panel for an archetype-only type."""
    cat_id = _id_for(edef.ext_type)
    label = edef.label
    target_fn = _make_get_target(edef.ext_type, get_selected_extension)
    poll_fn = _make_poll(edef.ext_type, get_selected_extension, label)

    category = PresetCategory(
        id=cat_id,
        label=label,
        game="gta5",
        bundled_defaults_path=Path(__file__).parent / f"{cat_id}_presets.json",
        get_target=target_fn,
        poll=poll_fn,
    )
    register_preset_category(category)

    slug = edef.ext_type.name.lower()

    save_cls = type(
        f"SOLLUMZ_OT_save_{slug}_ext_preset",
        (PresetSaveOperatorBase, bpy.types.Operator),
        {
            "bl_idname": f"sollumz.save_{slug}_ext_preset",
            "bl_label": f"Save {label} Extension Preset",
            "bl_description": f"Save current {label.lower()} extension as a named preset",
            "category": category,
        },
    )
    load_cls = type(
        f"SOLLUMZ_OT_load_{slug}_ext_preset",
        (PresetLoadOperatorBase, bpy.types.Operator),
        {
            "bl_idname": f"sollumz.load_{slug}_ext_preset",
            "bl_label": f"Apply {label} Extension Preset",
            "bl_description": f"Apply a saved {label.lower()} extension preset",
            "category": category,
        },
    )
    delete_cls = type(
        f"SOLLUMZ_OT_delete_{slug}_ext_preset",
        (PresetDeleteOperatorBase, bpy.types.Operator),
        {
            "bl_idname": f"sollumz.delete_{slug}_ext_preset",
            "bl_label": f"Delete {label} Extension Preset",
            "bl_description": f"Remove a saved {label.lower()} extension preset",
            "category": category,
        },
    )
    panel_cls = type(
        f"SOLLUMZ_PT_{slug}_ext_presets",
        (PresetPanel, bpy.types.Panel),
        {
            "bl_label": f"{label} Extension Presets",
            "category": category,
            "save_operator": save_cls.bl_idname,
            "load_operator": load_cls.bl_idname,
            "delete_operator": delete_cls.bl_idname,
        },
    )

    EXTENSION_PRESET_PANEL_BY_TYPE_AND_HOST[(edef.ext_type, HOST_ARCHETYPE)] = panel_cls
    return [save_cls, load_cls, delete_cls, panel_cls]


def _make_entity_classes(edef: _ExtDef):
    """Create category + 6 operators + 2 panels for an entity-only type.

    One operator triplet + panel is bound to the MLO entity host, the other
    to the map entity host. Both share the same `PresetCategory`, so the JSON
    storage is one file per type.
    """
    cat_id = _id_for(edef.ext_type)
    label = edef.label
    slug = edef.ext_type.name.lower()

    # Category target/poll defaults to the MLO context.
    # The map-entity operators override get_target and poll.
    mlo_target = _make_get_target(edef.ext_type, get_selected_entity_extension)
    mlo_poll = _make_poll(edef.ext_type, get_selected_entity_extension, label)
    map_target = _make_get_target(edef.ext_type, map_context.active_entity_extension)

    category = PresetCategory(
        id=cat_id,
        label=label,
        game="gta5",
        bundled_defaults_path=Path(__file__).parent / f"{cat_id}_presets.json",
        get_target=mlo_target,
        poll=mlo_poll,
    )
    register_preset_category(category)

    classes = []

    def _make_operators_and_panel(host: str, target_fn, suffix: str):
        save_cls = type(
            f"SOLLUMZ_OT_save_{slug}_ext_{suffix}_preset",
            (PresetSaveOperatorBase, bpy.types.Operator),
            {
                "bl_idname": f"sollumz.save_{slug}_ext_{suffix}_preset",
                "bl_label": f"Save {label} Extension Preset",
                "bl_description": f"Save current {label.lower()} extension as a named preset",
                "category": category,
                "get_target": target_fn,
                "poll": _make_op_poll(target_fn, label),
            },
        )
        load_cls = type(
            f"SOLLUMZ_OT_load_{slug}_ext_{suffix}_preset",
            (PresetLoadOperatorBase, bpy.types.Operator),
            {
                "bl_idname": f"sollumz.load_{slug}_ext_{suffix}_preset",
                "bl_label": f"Apply {label} Extension Preset",
                "bl_description": f"Apply a saved {label.lower()} extension preset",
                "category": category,
                "get_target": target_fn,
                "poll": _make_op_poll(target_fn, label),
            },
        )
        delete_cls = type(
            f"SOLLUMZ_OT_delete_{slug}_ext_{suffix}_preset",
            (PresetDeleteOperatorBase, bpy.types.Operator),
            {
                "bl_idname": f"sollumz.delete_{slug}_ext_{suffix}_preset",
                "bl_label": f"Delete {label} Extension Preset",
                "bl_description": f"Remove a saved {label.lower()} extension preset",
                "category": category,
            },
        )
        panel_cls = type(
            f"SOLLUMZ_PT_{slug}_ext_{suffix}_presets",
            (PresetPanel, bpy.types.Panel),
            {
                "bl_label": f"{label} Extension Presets",
                "category": category,
                "save_operator": save_cls.bl_idname,
                "load_operator": load_cls.bl_idname,
                "delete_operator": delete_cls.bl_idname,
            },
        )
        EXTENSION_PRESET_PANEL_BY_TYPE_AND_HOST[(edef.ext_type, host)] = panel_cls
        return [save_cls, load_cls, delete_cls, panel_cls]

    classes.extend(_make_operators_and_panel(HOST_MLO_ENTITY, mlo_target, "mlo"))
    classes.extend(_make_operators_and_panel(HOST_MAP_ENTITY, map_target, "map"))
    return classes


# Build all categories + operator/panel classes at module load. Inject into
# globals() so auto_load's per-module dict scan finds them.
def _build_all():
    all_classes = []
    for edef in _ARCHETYPE_EXTENSIONS:
        all_classes.extend(_make_archetype_classes(edef))
    for edef in _ENTITY_EXTENSIONS:
        all_classes.extend(_make_entity_classes(edef))
    g = globals()
    for cls in all_classes:
        g[cls.__name__] = cls


_build_all()
